stages:
  candidate_prepare:
    cmd: python steps/1_preparation/candinates_preparation.py data/djinni data/prepared
    deps:
    - data/djinni
    - steps/1_preparation/
    - steps/1_preparation/candinates_preparation.py
    outs:
    - data/prepared
    params:
    - candidate_prepare.input_file
    - candidate_prepare.output_file